from __future__ import annotations

# Generated from 2025_Success_Fee_Pricing.pdf. Rates are the published success fee percentages.
SUCCESS_FEE_RULES: tuple[tuple[str, str, float], ...] = (
    ('Liquor', 'Beer', 0.07),
    ('Liquor', 'Ciders & RTDs', 0.07),
    ('Liquor', 'Non-alcoholic', 0.07),
    ('Liquor', 'Spirits', 0.07),
    ('Liquor', 'Wine', 0.07),
    ('Liquor', 'Other', 0.07),
    ('Spirits', 'Cognac', 0.1),
    ('Spirits', 'Other', 0.07),
    ('Audio', 'Radio', 0.06),
    ('Audio', 'Amplifiers', 0.07),
    ('Audio', 'Microphones', 0.07),
    ('Audio', 'MP3 Players', 0.07),
    ('Audio', 'Hi-Fi Related', 0.08),
    ('Audio', 'Home Audio', 0.08),
    ('Audio', 'Speakers', 0.08),
    ('Audio', 'Headphones & Headsets', 0.12),
    ('Audio', 'Other', 0.12),
    ('TV & Audio', 'TV (if price <= R2999)', 0.055),
    ('TV & Audio', 'TV (if price > R2999 and <= 29999)', 0.07),
    ('TV & Audio', 'TV (if price > R29999 and <= R49999)', 0.085),
    ('TV & Audio', 'TV (if price > R49999)', 0.095),
    ('TV & Audio', 'Audio (if price <= R950)', 0.12),
    ('TV & Audio', 'Audio (if price > R950)', 0.09),
    ('TV & Audio', 'Accessories', 0.12),
    ('TV & Audio', 'Video', 0.12),
    ('TV & Audio', 'Other', 0.12),
    ('Baby', 'Baby Food', 0.12),
    ('Baby', 'Mom & Baby Care', 0.12),
    ('Baby', 'Baby Food & Nutrition', 0.12),
    ('Baby', 'Baby Equipment & Furniture', 0.14),
    ('Baby', 'Nappies & Changing', 0.14),
    ('Baby', 'Baby Clothing', 0.15),
    ('Baby', 'Other', 0.14),
    ('Beauty', 'Body Care', 0.12),
    ('Beauty', 'Hair Care', 0.12),
    ('Beauty', 'Skin Care', 0.12),
    ('Beauty', 'Cosmetics', 0.14),
    ('Beauty', 'Fragrances', 0.15),
    ('Beauty', 'Other', 0.12),
    ('Body Care', 'Bags & Cases', 0.12),
    ('Body Care', 'Exfoliators & Scrubs', 0.12),
    ('Body Care', 'Moisturisers & Creams', 0.12),
    ('Body Care', 'Sets', 0.12),
    ('Body Care', 'Soap & Body Wash', 0.12),
    ('Body Care', 'Tanning Products', 0.12),
    ('Body Care', 'Treatments', 0.12),
    ('Body Care', 'Tools', 0.12),
    ('Body Care', 'Other', 0.12),
    ('Hair Care', 'Electrical Beauty', 0.1),
    ('Hair Care', 'Conditioner', 0.12),
    ('Hair Care', 'Extensions, Wigs & Accessories', 0.12),
    ('Hair Care', 'Hair Colour', 0.12),
    ('Hair Care', 'Shampoo', 0.12),
    ('Hair Care', 'Styling Products', 0.12),
    ('Hair Care', 'Styling Tools', 0.12),
    ('Hair Care', 'Treatments', 0.12),
    ('Hair Care', 'Other', 0.12),
    ('Skin Care', 'Cleansers', 0.12),
    ('Skin Care', 'Exfoliator & Scrubs', 0.12),
    ('Skin Care', 'Masks', 0.12),
    ('Skin Care', 'Moisturisers', 0.12),
    ('Skin Care', 'Sets', 0.12),
    ('Skin Care', 'Treatments', 0.12),
    ('Skin Care', 'Toners', 0.12),
    ('Skin Care', 'Tools', 0.12),
    ('Skin Care', 'Other', 0.12),
    ('Cosmetics', 'Eyes', 0.14),
    ('Cosmetics', 'Face', 0.14),
    ('Cosmetics', 'Lips', 0.14),
    ('Cosmetics', 'Nails', 0.14),
    ('Cosmetics', 'Sets', 0.14),
    ('Cosmetics', 'Tools', 0.14),
    ('Cosmetics', 'Other', 0.12),
    ('Binoculars & Scopes', 'Microscopes', 0.08),
    ('Binoculars & Scopes', 'Monoculars', 0.08),
    ('Binoculars & Scopes', 'Spotting Scopes', 0.08),
    ('Binoculars & Scopes', 'Telescopes', 0.08),
    ('Binoculars & Scopes', 'Binoculars', 0.1),
    ('Binoculars & Scopes', 'Range Finders', 0.1),
    ('Binoculars & Scopes', 'Accessories', 0.12),
    ('Binoculars & Scopes', 'Other', 0.12),
    ('Certified Pre-Owned Electronics', 'Certified Pre-Owned Audio', 0.1),
    ('Certified Pre-Owned Electronics', 'Certified Pre-Owned Camera', 0.1),
    ('Certified Pre-Owned Electronics', 'Certified Pre-Owned Camera Lenses', 0.1),
    ('Certified Pre-Owned Electronics', 'Certified Pre-Owned Laptops', 0.1),
    ('Certified Pre-Owned Electronics', 'Certified Pre-Owned Mobile Devices', 0.1),
    ('Certified Pre-Owned Electronics', 'Certified Pre-Owned PC’s', 0.1),
    ('Certified Pre-Owned Electronics', 'Certified Pre-Owned Printers', 0.1),
    ('Certified Pre-Owned Electronics', 'Certified Pre-Owned Wearables', 0.1),
    ('Certified Pre-Owned Electronics', 'Other', 0.1),
    ('Computer Components', 'CPU', 0.06),
    ('Computer Components', 'Cases', 0.06),
    ('Computer Components', 'Fans & Cooling', 0.06),
    ('Computer Components', 'Interface Cards', 0.06),
    ('Computer Components', 'Optical Drive', 0.06),
    ('Computer Components', 'Sound Card', 0.06),
    ('Computer Components', 'Computer Memory', 0.07),
    ('Computer Components', 'Graphics Card', 0.07),
    ('Computer Components', 'Motherboard', 0.07),
    ('Computer Components', 'Power Supplies', 0.07),
    ('Computer Components', 'Cleaning & Repairs', 0.08),
    ('Computer Components', 'Components', 0.08),
    ('Computer Components', 'Accessories & Peripherals', 0.09),
    ('Computer Components', 'Data Storage', 0.1),
    ('Computer Components', 'Other', 0.07),
    ('Computer Monitors & Accessories', 'Computer Monitors', 0.06),
    ('Computer Monitors & Accessories', 'Gaming Monitors', 0.06),
    ('Computer Monitors & Accessories', 'Large Format Displays', 0.06),
    ('Computer Monitors & Accessories', 'Monitor Cleaning', 0.06),
    ('Computer Monitors & Accessories', 'Computer Monitor Accessories', 0.08),
    ('Computer Monitors & Accessories', 'Monitor Mounts & Brackets', 0.08),
    ('Computer Monitors & Accessories', 'Monitor Risers', 0.08),
    ('Computer Monitors & Accessories', 'Other', 0.05),
    ('Computers & Laptops', 'Software', 0.05),
    ('Computers & Laptops', 'Computer Monitor', 0.06),
    ('Computers & Laptops', 'Desktop computers & Workstations', 0.06),
    ('Computers & Laptops', 'Computer Monitor Accessories', 0.08),
    ('Computers & Laptops', 'Other', 0.05),
    ('Data Storage', 'Blank Media', 0.08),
    ('Data Storage', 'Harddrive', 0.08),
    ('Data Storage', 'USB Flash Devices', 0.1),
    ('Data Storage', 'Other', 0.1),
    ('Desktop Computers & Workstations', 'Gaming PC', 0.06),
    ('Desktop Computers & Workstations', 'Mini PC', 0.06),
    ('Desktop Computers & Workstations', 'Workstations', 0.06),
    ('Desktop Computers & Workstations', 'Laptops', 0.07),
    ('Desktop Computers & Workstations', 'All-in-One', 0.07),
    ('Desktop Computers & Workstations', 'Desktop Computers', 0.07),
    ('Desktop Computers & Workstations', 'Other', 0.06),
    ('Laptop Accessories', 'Batteries', 0.1),
    ('Laptop Accessories', 'Cooling Pads', 0.1),
    ('Laptop Accessories', 'Chargers & Adapters', 0.1),
    ('Laptop Accessories', 'Docking Stations', 0.1),
    ('Laptop Accessories', 'Bags & Cases', 0.14),
    ('Laptop Accessories', 'Covers & Sleeves', 0.14),
    ('Laptop Accessories', 'Mounts & Stands', 0.14),
    ('Laptop Accessories', 'Screen Protection & Privacy', 0.14),
    ('Laptop Accessories', 'Memory Card Readers', 0.14),
    ('Laptop Accessories', 'Keyboard Covers', 0.14),
    ('Laptop Accessories', 'Memory Cards', 0.14),
    ('Laptop Accessories', 'Power Banks', 0.14),
    ('Laptop Accessories', 'Skins & Decals', 0.14),
    ('Laptop Accessories', 'Security Locks', 0.14),
    ('Laptop Accessories', 'Other', 0.14),
    ('Networking', 'Access Points & Routers', 0.07),
    ('Networking', 'Extenders', 0.07),
    ('Networking', 'Modems', 0.07),
    ('Networking', 'Network Adapters & Hardware', 0.07),
    ('Networking', 'Switches, Cables & Servers', 0.07),
    ('Networking', 'USB Devices', 0.07),
    ('Networking', 'Other', 0.07),
    ('Electronic Accessories', 'Cleaning & Repairs', 0.1),
    ('Electronic Accessories', 'Cellular Accessories', 0.14),
    ('Electronic Accessories', 'Laptop Accessories', 0.14),
    ('Electronic Accessories', 'Other', 0.14),
    ('Smart Accessories', 'Cables', 0.12),
    ('Smart Accessories', 'Cases', 0.12),
    ('Smart Accessories', 'Charging Devices', 0.12),
    ('Smart Accessories', 'Docking Stations', 0.12),
    ('Smart Accessories', 'Screen Protectors', 0.14),
    ('Smart Accessories', 'Straps & Bands', 0.14),
    ('Smart Accessories', 'Other', 0.12),
    ('Tablet & E-reader Accessories', 'E-reader Accessories', 0.12),
    ('Tablet & E-reader Accessories', 'Tablet Accessories', 0.12),
    ('Tablet & E-reader Accessories', 'Other', 0.12),
    ('Clothing & Footwear', 'Accessories', 0.15),
    ('Clothing & Footwear', 'Footwear', 0.15),
    ('Clothing & Footwear', 'Kids Clothing', 0.15),
    ('Clothing & Footwear', 'Kids Footwear and Accessories', 0.15),
    ('Clothing & Footwear', 'Mens Clothing', 0.15),
    ('Clothing & Footwear', 'Mens Footwear & Accessories', 0.15),
    ('Clothing & Footwear', 'Womens Clothing', 0.15),
    ('Clothing & Footwear', 'Womens Footwear & Accessories', 0.15),
    ('Clothing & Footwear', 'Other', 0.15),
    ('Footwear & Accessories', 'Kids Footwear & Accessories', 0.15),
    ('Footwear & Accessories', 'Mens Footwear & Accessories', 0.15),
    ('Footwear & Accessories', 'Womens Footwear & Accessories', 0.15),
    ('Footwear & Accessories', 'Other', 0.15),
    ('Jewellery & Watches', 'Jewellery (if price <= R950)', 0.18),
    ('Jewellery & Watches', 'Jewellery (if price > R950)', 0.1),
    ('Jewellery & Watches', 'Watches (if price <= R2450)', 0.18),
    ('Jewellery & Watches', 'Watches (if price > R2450)', 0.1),
    ('Jewellery & Watches', 'Other', 0.15),
    ('Games', 'Consoles', 0.055),
    ('Games', 'Game-Software', 0.1),
    ('Games', 'Gaming Accessories', 0.1),
    ('Games', 'Merchandise', 0.15),
    ('Games', 'Other', 0.1),
    ('Gaming Accessories', 'Gaming Chairs', 0.12),
    ('Gaming Accessories', 'Other', 0.1),
    ('Garden, Pool & Patio', 'Garden & Outdoor Consumables', 0.12),
    ('Garden, Pool & Patio', 'Braais & Outdoor Cooking', 0.13),
    ('Garden, Pool & Patio', 'Equipment', 0.14),
    ('Garden, Pool & Patio', 'Patio', 0.14),
    ('Garden, Pool & Patio', 'Pool & Spa', 0.14),
    ('Garden, Pool & Patio', 'Other', 0.14),
    ('Equipment', 'Lawn Mowers & Power Tools', 0.12),
    ('Equipment', 'Other', 0.14),
    ('Patio', 'Patio Furniture', 0.12),
    ('Patio', 'Other', 0.14),
    ('Health', 'Health FMCG', 0.1),
    ('Health', 'Personal Care FMCG', 0.1),
    ('Health', 'Health Care Devices', 0.11),
    ('Health', 'Personal Care Devices', 0.12),
    ('Health', 'Other', 0.1),
    ('Bedroom', 'Inners & Pillows', 0.15),
    ('Bedroom', 'Other', 0.15),
    ('Homeware', 'Paint & Supplies', 0.1),
    ('Homeware', 'Bathroom', 0.15),
    ('Homeware', 'Dining & Entertainment', 0.15),
    ('Homeware', 'Furniture', 0.15),
    ('Homeware', 'Home Decor', 0.15),
    ('Homeware', 'Kitchen', 0.15),
    ('Homeware', 'Office Accessories', 0.15),
    ('Homeware', 'Other', 0.15),
    ('Large Appliances', 'Washing & Drying', 0.08),
    ('Large Appliances', 'Fridges & Freezers', 0.08),
    ('Large Appliances', 'Stoves & ovens', 0.08),
    ('Large Appliances', 'Dishwashers', 0.1),
    ('Large Appliances', 'Parts & Accessories', 0.1),
    ('Large Appliances', 'Microwaves & Cookers', 0.1),
    ('Large Appliances', 'Other', 0.1),
    ('Small Appliances', 'Small Kitchen Appliances', 0.1),
    ('Small Appliances', 'Small Household Appliances', 0.1),
    ('Small Appliances', 'Speciality Appliances', 0.1),
    ('Small Appliances', 'Small Appliance Accessories & Consumables', 0.12),
    ('Small Appliances', 'Other', 0.1),
    ('Smart Home & Connected Living', 'Wearable', 0.09),
    ('Smart Home & Connected Living', 'GPS Devices', 0.1),
    ('Smart Home & Connected Living', 'Home Security', 0.1),
    ('Smart Home & Connected Living', 'Smart Audio Technology', 0.1),
    ('Smart Home & Connected Living', 'Smart Energy Solutions', 0.1),
    ('Smart Home & Connected Living', 'Smart Home & Appliance', 0.1),
    ('Smart Home & Connected Living', 'Smart Lighting', 0.1),
    ('Smart Home & Connected Living', 'Smart Accessories', 0.12),
    ('Smart Home & Connected Living', 'Other', 0.14),
    ('Luggage & Travel', 'Handbags & Wallets', 0.15),
    ('Luggage & Travel', 'Luggage', 0.15),
    ('Luggage & Travel', 'Travel Accessories', 0.15),
    ('Luggage & Travel', 'Other', 0.07),
    ('Books', 'Academic', 0.14),
    ('Books', 'E-books', 0.14),
    ('Books', 'Trade Books', 0.14),
    ('Books', 'Other', 0.14),
    ('Music & DVD', 'Movies', 0.1),
    ('Music & DVD', 'Music', 0.1),
    ('Music & DVD', 'TV Series', 0.1),
    ('Music & DVD', 'Merchandise', 0.15),
    ('Music & DVD', 'Other', 0.1),
    ('Video', 'Streaming Media Players', 0.09),
    ('Video', 'Blu-ray Disc Players', 0.1),
    ('Video', 'Decoders', 0.1),
    ('Video', 'DVD Players', 0.1),
    ('Video', 'Home Theatre Systems', 0.1),
    ('Video', 'Projectors', 0.1),
    ('Video', 'Other', 0.12),
    ('Mobile', 'Airtime & Contracts', 0.075),
    ('Mobile', 'Cellphones', 0.075),
    ('Mobile', 'Tablets & E-readers', 0.075),
    ('Mobile', 'Other', 0.08),
    ('Instruments', 'Accordions', 0.08),
    ('Instruments', 'Classical', 0.08),
    ('Instruments', 'DJ Equipment & Production', 0.08),
    ('Instruments', 'DJ & Lighting', 0.08),
    ('Instruments', 'Drums & Percussion', 0.08),
    ('Instruments', 'Guitars', 0.08),
    ('Instruments', 'Harmonics', 0.08),
    ('Instruments', 'Melodica', 0.08),
    ('Instruments', 'Keyboards', 0.09),
    ('Instruments', 'Other', 0.12),
    ('Musical Instruments', 'Sound & Stage', 0.08),
    ('Musical Instruments', 'Instruments', 0.09),
    ('Musical Instruments', 'Accessories', 0.12),
    ('Musical Instruments', 'Other', 0.12),
    ('Non- Perishable', 'Food & Beverages', 0.08),
    ('Non- Perishable', 'Groceries', 0.08),
    ('Non- Perishable', 'Household Cleaning', 0.08),
    ('Non- Perishable', 'Other', 0.08),
    ('Home & Office Electronics', 'Projectors', 0.07),
    ('Home & Office Electronics', 'Shredders', 0.07),
    ('Home & Office Electronics', 'Label Makers', 0.1),
    ('Home & Office Electronics', 'Laminators', 0.1),
    ('Home & Office Electronics', 'Phone Accessories', 0.1),
    ('Home & Office Electronics', 'Phone Peripherals', 0.1),
    ('Home & Office Electronics', 'Phones & VOIP', 0.1),
    ('Home & Office Electronics', 'Point-of-Sale Equipment', 0.1),
    ('Home & Office Electronics', 'Projector Accessories', 0.1),
    ('Home & Office Electronics', 'Trimmers & Guillotines', 0.1),
    ('Home & Office Electronics', 'Voice Recorders & Accessories', 0.1),
    ('Home & Office Electronics', 'Calculators', 0.12),
    ('Home & Office Electronics', 'Other', 0.1),
    ('Office', 'Home & Office Electronics', 0.1),
    ('Office', 'Office Consumables', 0.1),
    ('Office', 'Printer, Scanner, Copier', 0.12),
    ('Office', 'Other', 0.1),
    ('Office Accessories', 'Board & Easels', 0.1),
    ('Office Accessories', 'Other', 0.1),
    ('Office Furniture & Storage', 'Cabinets', 0.1),
    ('Office Furniture & Storage', 'Chairs & Seating', 0.1),
    ('Office Furniture & Storage', 'Ergonomics', 0.1),
    ('Office Furniture & Storage', 'Storage & Shelving', 0.1),
    ('Office Furniture & Storage', 'Tables & Desks', 0.1),
    ('Office Furniture & Storage', 'Other', 0.15),
    ('Printers, Scanner, Copier', 'Copier', 0.07),
    ('Printers, Scanner, Copier', 'Printers', 0.1),
    ('Printers, Scanner, Copier', 'Scanners', 0.1),
    ('Printers, Scanner, Copier', 'Printer Accessories', 0.12),
    ('Printers, Scanner, Copier', 'Scanner Accessories', 0.12),
    ('Printers, Scanner, Copier', 'Other', 0.1),
    ('Outdoor Accessories', 'Electrical Accessories', 0.1),
    ('Outdoor Accessories', 'Deep Cycle Batteries', 0.1),
    ('Outdoor Accessories', 'Generators', 0.1),
    ('Outdoor Accessories', 'Rifle & Related Gear', 0.1),
    ('Outdoor Accessories', 'Ropes & Cords', 0.1),
    ('Outdoor Accessories', 'Cables & Plugs', 0.12),
    ('Outdoor Accessories', 'Emergency & Survival', 0.12),
    ('Outdoor Accessories', 'Power Conversions', 0.12),
    ('Outdoor Accessories', 'Knives & Tools', 0.15),
    ('Outdoor Accessories', 'Navigation & GPS Devices', 0.15),
    ('Outdoor Accessories', 'Health & Hygiene', 0.15),
    ('Outdoor Accessories', 'Other', 0.15),
    ('Camping & Outdoor', 'Fishing Equipment', 0.08),
    ('Camping & Outdoor', 'Hunting Apparel & Footwear', 0.12),
    ('Camping & Outdoor', 'Outdoor Kitchen', 0.12),
    ('Camping & Outdoor', 'Accessories', 0.15),
    ('Camping & Outdoor', 'Camping Furniture', 0.15),
    ('Camping & Outdoor', 'Lighting & Gadgets', 0.15),
    ('Camping & Outdoor', 'Sleeping', 0.15),
    ('Camping & Outdoor', 'Storage & Packs', 0.15),
    ('Camping & Outdoor', 'Tents & Shelters', 0.15),
    ('Camping & Outdoor', 'Other', 0.15),
    ('Lighting & Gadgets', 'Strips & Candles', 0.12),
    ('Lighting & Gadgets', 'Fans', 0.12),
    ('Lighting & Gadgets', 'Accessories', 0.15),
    ('Lighting & Gadgets', 'Headlamps', 0.15),
    ('Lighting & Gadgets', 'Spot Lights', 0.15),
    ('Lighting & Gadgets', 'Other', 0.15),
    ('Outdoor Kitchen', 'Coolers & Refrigeration', 0.1),
    ('Outdoor Kitchen', 'Basins & Drain Racks', 0.12),
    ('Outdoor Kitchen', 'Castiron', 0.12),
    ('Outdoor Kitchen', 'Cookers & Grills', 0.12),
    ('Outdoor Kitchen', 'Cookware & Cutlery', 0.12),
    ('Outdoor Kitchen', 'Gas Equipment', 0.12),
    ('Outdoor Kitchen', 'Other', 0.15),
    ('Storage & Packs', 'Water Storage & Sanitisation', 0.12),
    ('Storage & Packs', 'Packing Solutions & Accessories', 0.15),
    ('Storage & Packs', 'Storage Bags, Boxes & Liners', 0.15),
    ('Storage & Packs', 'Other', 0.15),
    ('Pets', 'Equipment & Accessories', 0.1),
    ('Pets', 'Food & Treats', 0.1),
    ('Pets', 'Pet Care Supplies', 0.1),
    ('Pets', 'Other', 0.1),
    ('Action Cams & Drones', 'Action Cameras', 0.05),
    ('Action Cams & Drones', 'Drones', 0.08),
    ('Action Cams & Drones', 'Camera Accessories', 0.12),
    ('Action Cams & Drones', 'Drone Accessories', 0.12),
    ('Action Cams & Drones', 'Other', 0.12),
    ('Cameras', 'Action Cams & Drones', 0.12),
    ('Cameras', 'Binoculars & Scopes', 0.12),
    ('Cameras', 'Other', 0.12),
    ('Cameras & Lenses', 'Cameras', 0.04),
    ('Cameras & Lenses', 'Lenses', 0.04),
    ('Cameras & Lenses', 'Lens Accessories', 0.07),
    ('Cameras & Lenses', 'Camera Accessories', 0.12),
    ('Cameras & Lenses', 'Other', 0.12),
    ('Video Cameras', 'Video Cameras', 0.06),
    ('Video Cameras', 'Video Camera Accessories', 0.12),
    ('Video Cameras', 'Other', 0.12),
    ('Software', 'Business & Office', 0.05),
    ('Software', 'Downloads', 0.05),
    ('Software', 'Multimedia', 0.05),
    ('Software', 'Security & Anti-Virus', 0.05),
    ('Software', 'Design & Creative Software', 0.05),
    ('Software', 'Educational', 0.05),
    ('Software', 'Other', 0.05),
    ('Sport', 'Consumables', 0.12),
    ('Sport', 'Equipment', 0.13),
    ('Sport', 'Accessories', 0.15),
    ('Sport', 'Clothing', 0.15),
    ('Sport', 'Footwear', 0.15),
    ('Sport', 'Other', 0.15),
    ('Stationery', 'Files, Tags, Labelling & Binders', 0.1),
    ('Stationery', 'Writing & Drawing Tools', 0.1),
    ('Stationery', 'Adhesives', 0.1),
    ('Stationery', 'Paper', 0.1),
    ('Stationery', 'Gifting', 0.1),
    ('Stationery', 'Scrapbooking & Papercraft', 0.1),
    ('Stationery', 'Art & Craft Supplies', 0.1),
    ('Stationery', 'General Stationery', 0.1),
    ('Stationery', 'Christmas', 0.14),
    ('Stationery', 'Other', 0.1),
    ('Automotive', 'Automotive Parts & Accessories', 0.1),
    ('Automotive', 'Motorcycle Parts & Accessories', 0.1),
    ('Automotive', 'Workshop & Maintenance', 0.1),
    ('Automotive', 'Other', 0.12),
    ('DIY & Automotive', 'Tools & Machinery', 0.1),
    ('DIY & Automotive', 'Home Improvement', 0.11),
    ('DIY & Automotive', 'Other', 0.1),
    ('Toys', 'Games & Puzzles', 0.12),
    ('Toys', 'Indoor Play', 0.12),
    ('Toys', 'Outdoor Play', 0.12),
    ('Toys', 'Smart Toys', 0.12),
    ('Toys', 'Other', 0.12),
    ('Wearable', 'Security Tracker Devices', 0.12),
    ('Wearable', 'Fitness & Activity Smart Watches (if price <= R1450)', 0.15),
    ('Wearable', 'Fitness & Activity Smart Watches (if price > R1450)', 0.1),
    ('Wearable', 'Health Tracker Devices (if price <= R1450)', 0.15),
    ('Wearable', 'Health Tracker Devices (if price > R1450)', 0.1),
    ('Wearable', 'Other', 0.07),
)
