"""add fulfillment draft tables

Revision ID: fc30eed42e6b
Revises: 
Create Date: 2026-04-16 15:16:37.396735
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc30eed42e6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fulfillment_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_binding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('shipment_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('po_number', sa.String(length=100), server_default='', nullable=False),
    sa.Column('due_date', sa.String(length=50), server_default='', nullable=False),
    sa.Column('facility_code', sa.String(length=100), server_default='', nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('package_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('total_weight_kg', sa.Float(), server_default='0', nullable=False),
    sa.Column('length_cm', sa.Float(), server_default='0', nullable=False),
    sa.Column('width_cm', sa.Float(), server_default='0', nullable=False),
    sa.Column('height_cm', sa.Float(), server_default='0', nullable=False),
    sa.Column('decl_currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('sender_country', sa.String(length=100), server_default='中国', nullable=False),
    sa.Column('bill_files', sa.Text(), server_default='', nullable=False),
    sa.Column('delivery_address', sa.Text(), server_default='', nullable=False),
    sa.Column('selected_cnx_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('selected_cnx_line_id', sa.Integer(), nullable=True),
    sa.Column('cnx_order_no', sa.String(length=100), server_default='', nullable=False),
    sa.Column('cnx_forecasted_at', sa.DateTime(), nullable=True),
    sa.Column('workflow_status', sa.String(length=30), server_default='待用户预报快递', nullable=False),
    sa.Column('warehouse_received_complete', sa.Integer(), server_default='0', nullable=False),
    sa.Column('labels_done', sa.Integer(), server_default='0', nullable=False),
    sa.Column('labels_done_at', sa.DateTime(), nullable=True),
    sa.Column('sent_to_cnx', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_to_cnx_at', sa.DateTime(), nullable=True),
    sa.Column('notify_user_cnx_at', sa.DateTime(), nullable=True),
    sa.Column('warehouse_note', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_username', sa.String(length=255), server_default='', nullable=False),
    sa.Column('updated_by_role', sa.String(length=50), server_default='', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_binding_id'], ['store_bindings.id'], name=op.f('fk_fulfillment_drafts_store_binding_id_store_bindings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_fulfillment_drafts_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fulfillment_drafts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillment_drafts')),
    sa.UniqueConstraint('store_binding_id', 'shipment_id', name='uq_fulfillment_store_shipment')
    )
    op.create_index(op.f('ix_fulfillment_drafts_shipment_id'), 'fulfillment_drafts', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_drafts_store_binding_id'), 'fulfillment_drafts', ['store_binding_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_drafts_user_id'), 'fulfillment_drafts', ['user_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_drafts_workflow_status'), 'fulfillment_drafts', ['workflow_status'], unique=False)
    op.create_table('fulfillment_audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), server_default='', nullable=False),
    sa.Column('role', sa.String(length=50), server_default='', nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_status', sa.String(length=30), server_default='', nullable=False),
    sa.Column('new_status', sa.String(length=30), server_default='', nullable=False),
    sa.Column('changes_json', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['fulfillment_drafts.id'], name=op.f('fk_fulfillment_audit_logs_draft_id_fulfillment_drafts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fulfillment_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillment_audit_logs'))
    )
    op.create_index(op.f('ix_fulfillment_audit_logs_created_at'), 'fulfillment_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_fulfillment_audit_logs_draft_id'), 'fulfillment_audit_logs', ['draft_id'], unique=False)
    op.create_table('fulfillment_draft_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('shipment_item_id', sa.String(length=100), server_default='', nullable=False),
    sa.Column('line_no', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sku', sa.String(length=100), server_default='', nullable=False),
    sa.Column('title', sa.Text(), server_default='', nullable=False),
    sa.Column('takealot_url', sa.Text(), server_default='', nullable=False),
    sa.Column('tsin_id', sa.String(length=100), server_default='', nullable=False),
    sa.Column('qty_required', sa.Integer(), server_default='0', nullable=False),
    sa.Column('qty_sending', sa.Integer(), server_default='1', nullable=False),
    sa.Column('arrived_qty', sa.Integer(), server_default='0', nullable=False),
    sa.Column('domestic_tracking_no', sa.String(length=255), server_default='', nullable=False),
    sa.Column('domestic_carrier', sa.String(length=100), server_default='', nullable=False),
    sa.Column('declared_en_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('declared_cn_name', sa.String(length=255), server_default='', nullable=False),
    sa.Column('hs_code', sa.String(length=50), server_default='', nullable=False),
    sa.Column('origin_country', sa.String(length=100), server_default='CN-China/中国', nullable=False),
    sa.Column('unit_price_usd', sa.Float(), server_default='0.1', nullable=False),
    sa.Column('unit_weight_kg', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('note', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['fulfillment_drafts.id'], name=op.f('fk_fulfillment_draft_items_draft_id_fulfillment_drafts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fulfillment_draft_items'))
    )
    op.create_index(op.f('ix_fulfillment_draft_items_draft_id'), 'fulfillment_draft_items', ['draft_id'], unique=False)
    op.create_index(op.f('ix_fulfillment_draft_items_sku'), 'fulfillment_draft_items', ['sku'], unique=False)
    op.create_index(op.f('ix_bid_log_created_at'), 'bid_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_bid_log_offer_id'), 'bid_log', ['offer_id'], unique=False)
    op.create_index(op.f('ix_bid_log_store_binding_id'), 'bid_log', ['store_binding_id'], unique=False)
    op.create_index(op.f('ix_bid_products_auto_bid_enabled'), 'bid_products', ['auto_bid_enabled'], unique=False)
    op.create_index(op.f('ix_bid_products_last_checked_at'), 'bid_products', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_bid_products_store_binding_id'), 'bid_products', ['store_binding_id'], unique=False)
    op.drop_index('ix_library_products_sort', table_name='library_products')
    op.create_index(op.f('ix_site_notifications_created_at'), 'site_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_site_notifications_is_read'), 'site_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_site_notifications_user_id'), 'site_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_store_bindings_is_active'), 'store_bindings', ['is_active'], unique=False)
    op.create_index(op.f('ix_store_bindings_user_id'), 'store_bindings', ['user_id'], unique=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_store_bindings_user_id'), table_name='store_bindings')
    op.drop_index(op.f('ix_store_bindings_is_active'), table_name='store_bindings')
    op.drop_index(op.f('ix_site_notifications_user_id'), table_name='site_notifications')
    op.drop_index(op.f('ix_site_notifications_is_read'), table_name='site_notifications')
    op.drop_index(op.f('ix_site_notifications_created_at'), table_name='site_notifications')
    op.create_index('ix_library_products_sort', 'library_products', [sa.text('completeness_score DESC'), sa.text('reviews_total DESC NULLS LAST')], unique=False)
    op.drop_index(op.f('ix_bid_products_store_binding_id'), table_name='bid_products')
    op.drop_index(op.f('ix_bid_products_last_checked_at'), table_name='bid_products')
    op.drop_index(op.f('ix_bid_products_auto_bid_enabled'), table_name='bid_products')
    op.drop_index(op.f('ix_bid_log_store_binding_id'), table_name='bid_log')
    op.drop_index(op.f('ix_bid_log_offer_id'), table_name='bid_log')
    op.drop_index(op.f('ix_bid_log_created_at'), table_name='bid_log')
    op.drop_index(op.f('ix_fulfillment_draft_items_sku'), table_name='fulfillment_draft_items')
    op.drop_index(op.f('ix_fulfillment_draft_items_draft_id'), table_name='fulfillment_draft_items')
    op.drop_table('fulfillment_draft_items')
    op.drop_index(op.f('ix_fulfillment_audit_logs_draft_id'), table_name='fulfillment_audit_logs')
    op.drop_index(op.f('ix_fulfillment_audit_logs_created_at'), table_name='fulfillment_audit_logs')
    op.drop_table('fulfillment_audit_logs')
    op.drop_index(op.f('ix_fulfillment_drafts_workflow_status'), table_name='fulfillment_drafts')
    op.drop_index(op.f('ix_fulfillment_drafts_user_id'), table_name='fulfillment_drafts')
    op.drop_index(op.f('ix_fulfillment_drafts_store_binding_id'), table_name='fulfillment_drafts')
    op.drop_index(op.f('ix_fulfillment_drafts_shipment_id'), table_name='fulfillment_drafts')
    op.drop_table('fulfillment_drafts')
    # ### end Alembic commands ###
